version: '3.8'

services:
  teamartemisIV:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: teamartemisIV_app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
