site_name: Movie Recommendation
site_description: "Recommending movies to users"
site_author: "Your name (or your team name)"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc
